FROM python:3.13.0b4-slim-bookworm

# Set env variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /app/django/count-app-v2

# Copy the requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

# Copy everything else
COPY . .

# Expose port
EXPOSE 8000

# Run the app
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]