services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: gunicorn --bind 0.0.0.0:8000 app.wsgi
    volumes:
      - .:/app/django/count-app-v2
    ports:
      - '8000:8000'