name: Build and Push a Docker Image
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Job 1 (Build the docker image)
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker compose build

  # Job 2 (Test the Image by running it)
  test:
    name: Test Docker Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Test the Image by running it
        run: docker compose up -d